### PR TITLE
Update membership from Ananya to Dan

### PR DESCRIPTION
**Pull request by angarg05**
Update membership from Ananya to Dan

Signed-off-by: Ananya Garg <ananyagarg@microsoft.com>

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
LGTM

Need approval from @vbatts for this one since he is other MSFT representative.

**Review by magowan — APPROVED** [review]
LGTM

**Review by vbatts — APPROVED** [review]

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by ariel-adam — APPROVED** [review]
Approved

**Comment by fidencio** [comment]
lgtm, thanks @angarg05!

As @vbatts approved the PR, I'm going ahead nd merging it!

**Pull request merged**
