### PR TITLE
WIP docs: Add a guide for IBM SE

### PR DESCRIPTION
**Pull request by BbolroC**
This is to add a guide to help users run/test a confidential containers with IBM Secure Execution.

Fixes: confidential-containers#100

### CODE REVIEW

**Comment by BbolroC** [comment]
This will be resumed after https://github.com/kata-containers/kata-containers/pull/7146 is finalized.

**Comment by magowan** [comment]
Hi @BbolroC 
Whats the status for this PR?
Do we have al the SE related docs in other places now?

**Review by magowan — COMMENTED** [review]
Hi @BbolroC
Whats the status for this PR?
Do we have al the SE related docs in other places now?

**Comment by BbolroC** [comment]
Oh, I forgot to close this PR. We have a cross-reference documentation for this:

- kata containers: https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-run-kata-containers-with-SE-VMs.md
- confidential containers (operator): https://github.com/confidential-containers/operator/blob/main/docs/how-to/INSTALL-CC-WITH-IBM-SE.md

**Pull request closed without merging**
