### PR TITLE
governance: Add Microsoft TSC members

### PR DESCRIPTION
**Pull request by surajssd**
- Add Vincent and Ananya to the list of members.

cc: @vbatts @angarg05

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @surajssd

**Review by vbatts — APPROVED** [review]
Happy to be involved!

**Review by fitzthum — APPROVED** [review]
# 🤝

**Comment by ariel-adam** [comment]
💪

**Review by ariel-adam — APPROVED** [review]

**Review by sameo — APPROVED** [review]

**Review by larrydewey — APPROVED** [review]

**Comment by sameo** [comment]
@peterzcst @magowan @dcmiddle Are you guys ok with this PR?

**Review by dcmiddle — APPROVED** [review]

**Comment by fitzthum** [comment]
Please rebase. I will wrangle the final SC approvals.

**Comment by zvonkok** [comment]
ping @surajssd please rebase

**Comment by surajssd** [comment]
Done 😄

**Review by jiangliu — APPROVED** [review]

**Review by fitzthum — APPROVED** [review]

**Comment by sameo** [comment]
I think we have a corum?

**Review by zvonkok — APPROVED** [review]
LGTM, welcome!

**Pull request merged**
