### PR TITLE
governance: Update governance.md, add NVIDIA TSC Member

### PR DESCRIPTION
**Pull request by zvonkok**
Add Zvonko Kaiser (NVIDIA) to the list of TSC members.

### CODE REVIEW

**Review by sameo — APPROVED** [review]

**Review by fitzthum — APPROVED** [review]

**Review by larrydewey — APPROVED** [review]
LGTM!

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by peterzcst — APPROVED** [review]
LGTM

**Comment by sameo** [comment]
@magowan @jiazhang0 @jiangliu @dcmiddle Are you ok with that PR?

**Review by dcmiddle — APPROVED** [review]

**Comment by fitzthum** [comment]
Ok, we have approvals on this PR from 2/3rds of TSC members, which meets the expansion requirements.

**Pull request merged**
