### PR TITLE
update readme + drop leftover images

### PR DESCRIPTION
**Pull request by mythi**
Instead, point users to check our release planning projects board.

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
The roadmap and the board aren't quite the same thing, but I am fine with this. We may need to add a real up-to-date roadmap document for incubationl.

**Review by dcmiddle — APPROVED** [review]

**Comment by mythi** [comment]
> We may need to add a real up-to-date roadmap document for incubationl.

apologies, I had missed that `roadmap.md` is a CNCF thing. I can also rework to update it a bit (instead of removing completely).

**Comment by fitzthum** [comment]
> I can also rework to update it a bit (instead of removing completely).

You might just keep the file there and replace the short-term roadmap with a link to the board.

**Comment by mythi** [comment]
> > I can also rework to update it a bit (instead of removing completely).
> 
> You might just keep the file there and replace the short-term roadmap with a link to the board.

AFAICS also the mid/long-term topics are outdated. Perhaps this is a good topic for the next TSC call?

**Comment by dcmiddle** [comment]
Is this good to merge? Don't want it sitting here and falling out of sync

**Comment by mythi** [comment]
> Is this good to merge? Don't want it sitting here and falling out of sync

from my side it is good to merge. I could work on the roadmap updates in a separate PR later.

**Pull request merged**
