### PR TITLE
guides: update enclave-cc notes for SGX hardware mode

### PR DESCRIPTION
**Pull request by mythi**
With #212 now closed we have a data point that things work fine when the environment is correct. However, we did identify some improvements needed to the docs. Those are added here.

With that, I'm also closing:

Closes: #220 
Closes: #224

Any follow-ups to be had in `Discussions`.

### CODE REVIEW

**Review by dcmiddle — APPROVED** [review]

**Review by fitzthum — APPROVED** [review]
LGTM

**Comment by mythi** [comment]
I have a PR coming for that `check links` issue

**Review by dcmiddle — APPROVED** [review]

**Comment by qiaofu1024** [comment]
Cool

**Comment by mythi** [comment]
> I have a PR coming for that `check links` issue

The fix is included in this PR so it would be good to get this merged to get other PRs also passing

**Pull request merged**
