### PR TITLE
ci: add link checker

### LINKED ISSUE #99: docs: add link checker to CI
Detect broken links like in #98 with a CI job.

### PR DESCRIPTION
**Pull request by katexochen**
Adding a workflow for checking for broken links. I'll fix the existing broken links in a separate PR as some of the fixes are non-trivial and might need discussion.

Fixes #99

### CODE REVIEW

**Comment by katexochen** [comment]
With the fix in #110, there are still 3 issues left to be fixed:

**Errors in ./CONTRIBUTING.md**

- [404] https://github.com/confidential-containers/.github/blob/main/scripts/pr-porting-checks.sh | Failed: Network error: Not Found
- [404] https://github.com/kata-containers/tests/tree/main/cmd/checkcommits | Failed: Network error: Not Found
- [404] https://github.com/confidential-containers/tests/blob/main/.ci/static-checks.sh | Failed: Network error: Not Found

**Comment by katexochen** [comment]
Checker is passing now that #160 is merged.

**Review by fitzthum — APPROVED** [review]
LGTM

**Review by dcmiddle — APPROVED** [review]
FWIW the identical commit seems to be working without issue in guest components.
https://github.com/confidential-containers/guest-components/pull/277

**Pull request merged**
